### ISSUE TITLE
TF2 notebook fails with read-only filesystem

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Tensorflow2#1]
The TF2 notebook https://github.com/zzweig/tensorflow2-graphcore/blob/main/get-started/run_cluster_gcn_notebook.ipynb fails with

```
OSError: [Errno 30] Read-only file system: '/graphcore/graph_datasets/ogbn_arxiv/processed/data_processed'
```

**Comment by nmb-paperspace** [comment]
`DATASET_DIR` in the notebook is `/graphcore`, as expected

**Comment by nmb-paperspace** [comment]
This was still happening a day later, so it was not an isolated error

**Comment by nmb-paperspace** [comment]
Deniz commented:

> We will change the relative path and will send a PR.

**Comment by internetoftim** [comment]
Requested to change` DATA_DIR=/tmp` unblocks read-only fs.
No code in the repo uses any cached executable or dataset, setting the variable to /tmp disables any form of caching.

**Comment by nmb-paperspace** [comment]
Reverting config.data_path as at https://github.com/zzweig/tensorflow2-graphcore/pull/6/commits/6a2d2f0887103ec37b6e5ce4e55bdf759d01f218 fixes this.
