### ISSUE TITLE
TF2 notebooks failing with missing NumPy attribute

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Tensorflow2#16]
The first cells in `learning-TensorFlow2-on-IPU/keras.ipynb` and `mnist.ipynb` fail with

`AttributeError: module 'numpy' has no attribute 'object'
`

(they were previously working)

**Comment by payoto** [comment]
I'll tackle that one. It seems it might be related to the new numpy release.

**Comment by rahult-graphcore** [comment]
PR opened which resolves this issue: https://github.com/gradient-ai/Graphcore-Tensorflow2/pull/17

**Comment by nmb-paperspace** [comment]
Yep I think this is good; will double-check then close

**Comment by nmb-paperspace** [comment]
Is indeed OK, so closing
